spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
    enabled: true

tables:
  - name: users
    columns:
      - name: user_id
        type: SERIAL
        primary_key: true
      - name: user_name
        type: VARCHAR(255)
      - name: user_pass
        type: VARCHAR(255)
      - name: user_age
        type: INT
      - name: user_email
        type: VARCHAR(255)
      - name: user_phone
        type: VARCHAR(28)
    data:
      - user_name: Nikita
        user_pass: "8984"
        user_age: 13
        user_email: nikitarussia27@gmail.com
        user_phone: "89995550323"
      - user_name: Alexey
        user_pass: "7956"
        user_age: 15
        user_email: nikitarussia27@gmail.com
        user_phone: "89047573734"
      - user_name: Sergey
        user_pass: "4567"
        user_age: 22
        user_email: nikitarussia27@gmail.com
        user_phone: "89080880782"
      - user_name: Vovan
        user_pass: "3224"
        user_age: 43
        user_email: nikitarussia27@gmail.com
        user_phone: "89954321221"
      - user_name: Fedya
        user_pass: "7689"
        user_age: 67
        user_email: nikitarussia27@gmail.com
        user_phone: "89062343221"

  - name: books
    columns:
      - name: book_id
        type: SERIAL
        primary_key: true
      - name: user_id
        type: INT
        foreign_key:
          references: users(user_id)
      - name: book_title
        type: VARCHAR(255)
    data:
      - book_id: 1
        user_id: 2
        book_title: Andersons tales
      - book_id: 2
        user_id: 2
        book_title: Anna Karenina
      - book_id: 3
        user_id: 1
        book_title: The Chronicles of Narnia
      - book_id: 4
        user_id: 1
        book_title: Walking through the torments

  - name: favorite_books
    columns:
      - name: favorite_book_id
        type: SERIAL
        primary_key: true
      - name: user_id
        type: INT
        foreign_key:
          references: users(user_id)
      - name: book_id
        type: INT
        foreign_key:
          references: books(book_id)
    data:
      - user_id: 3
        book_id: 4
      - user_id: 3
        book_id: 1
      - user_id: 3
        book_id: 3
      - user_id: 1
        book_id: 2

  - name: users1
    enums:
      passport_enum:
        - RUSSIAN
        - AMERICAN
        - GERMAN
        - FRENCH
        - JAPANESE
        - CHINESE
        - INDIAN
        - BRAZILIAN
        - CANADIAN
        - AUSTRALIAN
    columns:
      - name: id
        type: SERIAL
        primary_key: true
      - name: user_id
        type: INT
        foreign_key:
          references: users(user_id)
      - name: passport
        type: passport_enum
    data:
      - user_id: 1
        passport: RUSSIAN
      - user_id: 1
        passport: GERMAN
      - user_id: 3
        passport: AMERICAN
      - user_id: 2
        passport: CHINESE
      - user_id: 3
        passport: FRENCH
      - user_id: 4
        passport: JAPANESE
      - user_id: 4
        passport: CANADIAN
      - user_id: 2
        passport: BRAZILIAN
      - user_id: 1
        passport: INDIAN
      - user_id: 2
        passport: AUSTRALIAN