spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
    enabled: true

    databaseChangeLog:
      - changeSet:
          id: 1
          author: user
          changes:
            - createTable:
                tableName: users
                columns:
                  - column:
                      name: user_id
                      type: SERIAL
                      constraints:
                        primaryKey: true
                  - column:
                      name: user_name
                      type: VARCHAR(255)
                  - column:
                      name: user_pass
                      type: VARCHAR(255)
                  - column:
                      name: user_age
                      type: INT
                  - column:
                      name: user_email
                      type: VARCHAR(255)
                  - column:
                      name: user_phone
                      type: VARCHAR(28)

      - changeSet:
          id: 2
          author: user
          changes:
            - insert:
                tableName: users
                columns:
                  - column: { name: user_name, value: Nikita }
                  - column: { name: user_pass, value: '8984' }
                  - column: { name: user_age, valueNumeric: 13 }
                  - column: { name: user_email, value: nikitarussia27@gmail.com }
                  - column: { name: user_phone, value: '89995550323' }
            - insert:
                tableName: users
                columns:
                  - column: { name: user_name, value: Alexey }
                  - column: { name: user_pass, value: '7956' }
                  - column: { name: user_age, valueNumeric: 15 }
                  - column: { name: user_email, value: nikitarussia27@gmail.com }
                  - column: { name: user_phone, value: '89047573734' }
            - insert:
                tableName: users
                columns:
                  - column: { name: user_name, value: Sergey }
                  - column: { name: user_pass, value: '4567' }
                  - column: { name: user_age, valueNumeric: 22 }
                  - column: { name: user_email, value: nikitarussia27@gmail.com }
                  - column: { name: user_phone, value: '89080880782' }
            - insert:
                tableName: users
                columns:
                  - column: { name: user_name, value: Vovan }
                  - column: { name: user_pass, value: '3224' }
                  - column: { name: user_age, valueNumeric: 43 }
                  - column: { name: user_email, value: nikitarussia27@gmail.com }
                  - column: { name: user_phone, value: '89954321221' }
            - insert:
                tableName: users
                columns:
                  - column: { name: user_name, value: Fedya }
                  - column: { name: user_pass, value: '7689' }
                  - column: { name: user_age, valueNumeric: 67 }
                  - column: { name: user_email, value: nikitarussia27@gmail.com }
                  - column: { name: user_phone, value: '89062343221' }

      - changeSet:
          id: 3
          author: user
          changes:
            - createTable:
                tableName: books
                columns:
                  - column:
                      name: book_id
                      type: SERIAL
                      constraints:
                        primaryKey: true
                  - column:
                      name: user_id
                      type: INT
                      constraints:
                        foreignKeyName: fk_books_user
                        references: users(user_id)
                  - column:
                      name: book_title
                      type: VARCHAR(255)

      - changeSet:
          id: 4
          author: user
          changes:
            - insert:
                tableName: books
                columns:
                  - column: { name: book_id, valueNumeric: 1 }
                  - column: { name: user_id, valueNumeric: 2 }
                  - column: { name: book_title, value: Andersons tales }
            - insert:
                tableName: books
                columns:
                  - column: { name: book_id, valueNumeric: 2 }
                  - column: { name: user_id, valueNumeric: 2 }
                  - column: { name: book_title, value: Anna Karenina }
            - insert:
                tableName: books
                columns:
                  - column: { name: book_id, valueNumeric: 3 }
                  - column: { name: user_id, valueNumeric: 1 }
                  - column: { name: book_title, value: The Chronicles of Narnia }
            - insert:
                tableName: books
                columns:
                  - column: { name: book_id, valueNumeric: 4 }
                  - column: { name: user_id, valueNumeric: 1 }
                  - column: { name: book_title, value: Walking through the torments }

      - changeSet:
          id: 5
          author: user
          changes:
            - createTable:
                tableName: favorite_books
                columns:
                  - column:
                      name: favorite_book_id
                      type: SERIAL
                      constraints:
                        primaryKey: true
                  - column:
                      name: user_id
                      type: INT
                      constraints:
                        foreignKeyName: fk_favbooks_user
                        references: users(user_id)
                  - column:
                      name: book_id
                      type: INT
                      constraints:
                        foreignKeyName: fk_favbooks_book
                        references: books(book_id)

      - changeSet:
          id: 6
          author: user
          changes:
            - insert:
                tableName: favorite_books
                columns:
                  - column: { name: user_id, valueNumeric: 3 }
                  - column: { name: book_id, valueNumeric: 4 }
            - insert:
                tableName: favorite_books
                columns:
                  - column: { name: user_id, valueNumeric: 3 }
                  - column: { name: book_id, valueNumeric: 1 }
            - insert:
                tableName: favorite_books
                columns:
                  - column: { name: user_id, valueNumeric: 3 }
                  - column: { name: book_id, valueNumeric: 3 }
            - insert:
                tableName: favorite_books
                columns:
                  - column: { name: user_id, valueNumeric: 1 }
                  - column: { name: book_id, valueNumeric: 2 }

      - changeSet:
          id: 7
          author: user
          changes:
            - createType:
                catalogName: public
                typeName: passport_enum
                values:
                  - RUSSIAN
                  - AMERICAN
                  - GERMAN
                  - FRENCH
                  - JAPANESE
                  - CHINESE
                  - INDIAN
                  - BRAZILIAN
                  - CANADIAN
                  - AUSTRALIAN

      - changeSet:
          id: 8
          author: user
          changes:
            - createTable:
                tableName: users1
                columns:
                  - column:
                      name: id
                      type: SERIAL
                      constraints:
                        primaryKey: true
                  - column:
                      name: user_id
                      type: INT
                      constraints:
                        foreignKeyName: fk_users1_user
                        references: users(user_id)
                  - column:
                      name: passport
                      type: passport_enum
                      constraints:
                        nullable: false

      - changeSet:
          id: 9
          author: user
          changes:
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 1 }
                  - column: { name: passport, value: RUSSIAN }
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 1 }
                  - column: { name: passport, value: GERMAN }
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 3 }
                  - column: { name: passport, value: AMERICAN }
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 2 }
                  - column: { name: passport, value: CHINESE }
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 3 }
                  - column: { name: passport, value: FRENCH }
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 4 }
                  - column: { name: passport, value: JAPANESE }
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 4 }
                  - column: { name: passport, value: CANADIAN }
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 2 }
                  - column: { name: passport, value: BRAZILIAN }
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 1 }
                  - column: { name: passport, value: INDIAN }
            - insert:
                tableName: users1
                columns:
                  - column: { name: user_id, valueNumeric: 2 }
                  - column: { name: passport, value: AUSTRALIAN }